name: Test

on:
    push:
    pull_request:

jobs:
    test: 
        runs-on: ubuntu-latest
        name: Test
        steps:
          - name: Checkout
            uses: actions/checkout@master
          - name: Install Rokit
            uses: CompeyDev/setup-rokit@v0.2.1
          - name: Lute Lint
            run: lute lint
          - name: Lute Test
            run: lute test